# Generated by Django 3.0.14 on 2022-03-17 17:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_task_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 3, 17, 17, 46, 3, 354517, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
